name: Docker-k8s-todo-app CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.1.0

      - name: Login to Docker Hub
        uses: docker/login-action@v4.5.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Backend
        run: |
          docker build -f backend/Dockerfile -t mv7moud/todo-backend:latest .

      - name: Push Backend
        run: |
          docker push mv7moud/todo-backend:latest

      - name: Build Frontend
        run: |
          docker build -t mv7moud/todo-frontend:latest ./frontend

      - name: Push Frontend
        run: |
          docker push mv7moud/todo-frontend:latest
